"""Exceções de domínio do Ranggo.

Centraliza a hierarquia de erros de negócio do sistema. Toda exceção
levantada por um service deve herdar de :class:`RanggoError`, de modo
que a camada de UI possa capturar de forma uniforme e exibir mensagens
ao operador (dialog/snackbar) sem precisar conhecer cada subtipo.

Regras:
    * Services levantam exceções desta hierarquia — nunca ``Exception``
      genérica.
    * Repositories podem deixar vazar erros do SQLAlchemy; o service
      os converte para erros de domínio quando apropriado.
    * UI captura :class:`RanggoError` e mostra ``str(erro)`` ao usuário.
"""


class RanggoError(Exception):
    """Exceção raiz para todos os erros de domínio do Ranggo.

    Subclasses devem ser criadas em cada fase do roadmap, conforme
    novas regras de negócio forem implementadas. Esta classe não deve
    ser levantada diretamente — sempre use uma subclasse específica.
    """


# ---------------------------------------------------------------------------
# Hierarquia futura prevista (roteiro — adicionar conforme cada fase)
# ---------------------------------------------------------------------------
#
# Fase 1 — Autenticação:
#   class AutenticacaoError(RanggoError): ...
#       class LoginInvalidoError(AutenticacaoError): ...
#       class UsuarioInativoError(AutenticacaoError): ...
#       class PermissaoNegadaError(AutenticacaoError): ...
#
# Fase 2 — Cadastros:
#   class ValidacaoError(RanggoError): ...
#       class NomeDuplicadoError(ValidacaoError): ...
#       class ReferenciaInvalidaError(ValidacaoError): ...
#   class FichaTecnicaError(RanggoError): ...
#       class InsumoJaNaFichaError(FichaTecnicaError): ...
#
# Fase 3 — Venda Balcão / PDV:
#   class EstoqueError(RanggoError): ...
#       class EstoqueInsuficienteError(EstoqueError): ...
#   class VendaError(RanggoError): ...
#       class CarrinhoVazioError(VendaError): ...
#       class DescontoNaoPermitidoError(VendaError): ...
#   class ImpressaoError(RanggoError): ...
#       class ImpressoraIndisponivelError(ImpressaoError): ...
#
# Fase 4 — Comandas e Mesas:
#   class ComandaError(RanggoError): ...
#       class ComandaJaFechadaError(ComandaError): ...
#       class MesaOcupadaError(ComandaError): ...
#
# Fase 5 — Delivery / Relatórios / NFC-e:
#   class DeliveryError(RanggoError): ...
#       class EnderecoIncompletoError(DeliveryError): ...
#   class FiscalError(RanggoError): ...
#       class NFCeEmissaoError(FiscalError): ...
#
# ---------------------------------------------------------------------------
